// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0oi9HHvv0dWuNcbSFv1KeJux8ySDVuY4',
    appId: '1:401848299334:web:0e871e430dbc5bc70fbf47',
    messagingSenderId: '401848299334',
    projectId: 'todoappddd-ec246',
    authDomain: 'todoappddd-ec246.firebaseapp.com',
    storageBucket: 'todoappddd-ec246.appspot.com',
    measurementId: 'G-KJ1537D9XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8vixpciWc4uOi8tRN5z5IBVcDYKuOjc',
    appId: '1:401848299334:android:3fe458ad68eacff50fbf47',
    messagingSenderId: '401848299334',
    projectId: 'todoappddd-ec246',
    storageBucket: 'todoappddd-ec246.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR65d7GJk7WMvf79GXLMafr3IioW3pdx4',
    appId: '1:401848299334:ios:a9cb1ce7b29081720fbf47',
    messagingSenderId: '401848299334',
    projectId: 'todoappddd-ec246',
    storageBucket: 'todoappddd-ec246.appspot.com',
    iosClientId: '401848299334-sa567p0s74dfuudp7urcdumm1s1bk66f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR65d7GJk7WMvf79GXLMafr3IioW3pdx4',
    appId: '1:401848299334:ios:a9cb1ce7b29081720fbf47',
    messagingSenderId: '401848299334',
    projectId: 'todoappddd-ec246',
    storageBucket: 'todoappddd-ec246.appspot.com',
    iosClientId: '401848299334-sa567p0s74dfuudp7urcdumm1s1bk66f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
